in_dir: "/fs/ess/PAS1855/users/nghinguyen/FinalProject/Snakemake/data/"
out_dir: "/fs/ess/PAS1855/users/nghinguyen/FinalProject/Snakemake/results/"
log_dir: "/fs/ess/PAS1855/users/nghinguyen/FinalProject/Snakemake/log/"